#####
# AUTOMATIONS: This handles the loading of my automations via ui and manual
# https://www.home-assistant.io/docs/automation/
# https://www.home-assistant.io/docs/configuration/splitting_configuration/
#####

automation manual: !include_dir_merge_list ../automations

automation ui: !include ./../automations.yaml
