#####
# Home Assistant Configuration.yaml.
# By using packages: I'm pulling all other configuration files
# from individual folders, starting with Integrations
#####

homeassistant:
  packages: !include_dir_named integrations # package setup/config split

  # directory for camera snapshots
  allowlist_external_dirs:
    - "/config/snapshots"
    - "./snapshots"

#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

#input_number: !include input_number.yaml

#logger:
#default: warn

#todo: move
sun2:
  - unique_id: tanzania
    location: Lushoto,Tanzania
    latitude: -4.875124
    longitude: 38.462557
    time_zone: Africa/Nairobi

  - unique_id: home
