################################################################################
# Home Assistant Configuration
################################################################################

# Nothing to see here. Move along.
homeassistant:
  packages: !include_dir_named packages

#####
# Configures the official Home Assistant frontend.
# https://www.home-assistant.io/components/frontend/
#####

frontend:
  # We can define additional/custom themes for the frontend here.
  themes: !include_dir_merge_named themes
  #extra_module_url:
  #- /local/community/custom-brand-icons/custom-brand-icons.js
