#####
# Binary Sensor TODO
#####

#####
# FFmpeg Motion Detection
# Camera #1
# IP: xxx.xxx.x.22
#####
- platform: ffmpeg_motion
  entity_namespace: "ffmpeg_"
  name: "Motion Detection Camera #1"
  input: !secret camera_feed_1
  changes: 2
  repeat: 2
  repeat_time: 3

#####
# FFmpeg Motion Detection
# Camera #2
# IP: xxx.xxx.x.23
#####
#- platform: ffmpeg_motion
# entity_namespace: "ffmpeg_"
# name: "Motion Detection Camera #2"
#input: !secret camera_feed_2

# times of day sensor
- platform: tod
  name: Test Reptile Schedule
  after: sunrise
  after_offset: "2:00"
  before: sunset
  before_offset: "0:45"
  unique_id: test_rep_schedule
