#####
# Binary Sensor TODO
#####

#####
# FFmpeg Motion Detection
# Camera #1
# IP: xxx.xxx.x.22
#####
- platform: ffmpeg_motion
  entity_namespace: "ffmpeg_"
  name: "Motion Detection Camera #1"
  input: !secret camera_feed_1
  changes: 2
  repeat: 2
  repeat_time: 3
#####
# FFmpeg Motion Detection
# Camera #2
# IP: xxx.xxx.x.23
#####
- platform: ffmpeg_motion
  entity_namespace: "ffmpeg_"
  name: "Motion Detection Camera #2"
  input: !secret camera_feed_2
  changes: 2
  repeat: 2
  repeat_time: 3

#####
# FFmpeg Motion Detection
# Camera #3
# IP: xxx.xxx.x.23
#####
- platform: ffmpeg_motion
  entity_namespace: "ffmpeg_"
  name: "Motion Detection Camera #3"
  input: !secret camera_feed_3
  changes: 2
  repeat: 2
  repeat_time: 3

  #####
# FFmpeg Motion Detection
# Camera #4 360
# IP: xxx.xxx.x.23
#####
- platform: ffmpeg_motion
  entity_namespace: "ffmpeg_"
  name: "Motion Detection Camera #4"
  input: !secret camera_feed_4
  changes: 2
  repeat: 2
  repeat_time: 3
