
substitutions:
  itag1_id: white_itag_1
  itag1_friendly_name: "iTag 1"

  # Tag 2
  itag2_id: white_itag_2
  itag2_friendly_name: "iTag 2"

  atc_1_id: atc_hygrometer_1
  atc_1_friendly_name: "ATC Hygrometer 1"

esphome:
  name: bluetooth-upstairs-hub
  friendly_name: Bluetooth Upstairs Hub

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "UK183nZ61Ngi/7py/HnBtsMQURS8lYXnBke8iBepuFo="

ota:
  - platform: esphome
    password: "9261fadd458c420a7f03c4467a4be901"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth-Upstairs-Hub"
    password: "p5uecvmtRSN7"

captive_portal:
    


esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
  on_ble_advertise:
    - then:

bluetooth_proxy:
  active: true
  
ble_client:
 ### ===== ATC BLE CLIENT ===== ###
  - mac_address: A4:C1:38:CF:0F:45 # A4:C1:38:91:3B:D8 .  5B:09:83:FC:69:4C #REPLACE WITH FOB'S MAC ADDRESS "78:6D:EB:2D:BF:4C"
    id: ${atc_1_id}
    auto_connect: true
    on_connect:
      then:
        - logger.log: "${atc_1_friendly_name} is connected!!"

binary_sensor:
  - platform: ble_presence
    mac_address: A4:C1:38:91:3B:D8
    name: "${atc_1_friendly_name}"

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ${atc_1_id}
    name: "${atc_1_friendly_name} RSSI"
    entity_category: "diagnostic"

#text_sensor:
 # - platform: ble_scanner
   # name: "BLE Devices Scanner"

