esphome:
  name: bluetooth-tracker-hub
  friendly_name: Bluetooth Tracker Hub

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3v5G+An0eZnHLrGbwTzm9j2yei9ApcEyMQSoCV7VXRU="

ota:
  - platform: esphome
    password: "469984a95c5b44a188f0e0cd2c739c92"

wifi:
  ssid: "Snailicide"
  password: "Betta$11"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth-Tracker-Hub"
    password: "ULK0b2wdQEat"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
