substitutions:
  proxy_id: bluetooth_upstairs_hub
  proxy_friendly_name: Bluetooth Upstairs Hub

esphome:
  name: ${proxy_id}
  friendly_name: ${proxy_friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "UK183nZ61Ngi/7py/HnBtsMQURS8lYXnBke8iBepuFo="

ota:
  - platform: esphome
    password: "9261fadd458c420a7f03c4467a4be901"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth-Upstairs-Hub"
    password: "p5uecvmtRSN7"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: status
    id: ${proxy_id}_status
    name: "${proxy_friendly_name} Status"

sensor:
  ### =====ESP32 BLE Tracker Wifi Signal Strength===== ###
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: ${proxy_id}wifi_signal_db
    name: "${proxy_friendly_name} WiFi Signal dB"
    update_interval: 360s
    entity_category: "diagnostic"