substitutions:
  name: esp32-bluetooth-proxy-2c540c
  friendly_name: Bluetooth Proxy iTag
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esphome:
  name: gbt-ble-proxy

esp32:
  board: esp32dev
  framework:
    type: arduino
# Enable logging

logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
   # Set this to the IP of the ESP
   # static_ip: 192.168.1.27
   # gateway: 192.168.1.1
   # subnet: 255.255.255.0
   # Set this to the IP address of the router. Often ends with .1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bluetooth-Proxy-Test"
    password: "1WP9dKawnoWr"

captive_portal:


esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: atc_mithermometer
    mac_address: A4:C1:38:91:3B:D8
    temperature:
      name: "ATC Temperature"
    humidity:
      name: "ATC Humidity"
    battery_level:
      name: "ATC Battery-Level"
    battery_voltage:
      name: "ATC Battery-Voltage"
    signal_strength:
      name: "ATC Signal"
    