substitutions:
  itag_id: itag_test
  itag_friendly_name: "New White iTag Test"

esphome:
  name: itag-tracking-hub
  friendly_name: iTag Tracking Hub

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "e+ytaqwRnEX7Qgv2z/qmpmqH3HZ6GHWGbeo8izdjDm0="

ota:
  - platform: esphome
    password: "14db73ee4c1c59963281f375b78a2185"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Itag-Tracker-New"
    password: "TRdMP8ABF4bm"

captive_portal:

esp32_ble_tracker:

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: status
    name: "Status"
    id: signal_status
    entity_category: "diagnostic"

ble_client:
  - mac_address: 5B:09:83:FC:69:4C
    id: ${itag_id}
    auto_connect: true
    on_connect:
      then:
        - logger.log: "THE ITAG IS Connected"

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB\
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 360s
    entity_category: "diagnostic"


  - platform: ble_client
    type: characteristic
    ble_client_id: ${itag_id}
    name: "battery level"
    id: battery_level
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    icon: 'mdi:battery'
    unit_of_measurement: '%'

  - platform: ble_client
    type: rssi
    id: rssi
    ble_client_id: ${itag_id}
    name: "iTag RSSI"
