substitutions:
  itag_id: itag_test
  itag_friendly_name: "New White iTag Test"

esphome:
  name: itag-tracking-hub
  friendly_name: iTag Tracking Hub

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "e+ytaqwRnEX7Qgv2z/qmpmqH3HZ6GHWGbeo8izdjDm0="

ota:
  - platform: esphome
    password: "14db73ee4c1c59963281f375b78a2185"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Itag-Tracker-New"
    password: "TRdMP8ABF4bm"

captive_portal:

esp32_ble_tracker:
    on_ble_advertise:
    - then:

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: status
    name: "Status"
    id: signal_status
    entity_category: "diagnostic"

  # Presence based on MAC address
  - platform: ble_presence
    mac_address: 5B:09:83:FC:69:4C
    name: "ESP32 BLE Tracker Google Home Mini"
    min_rssi: -80dB
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB\
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 360s
    entity_category: "diagnostic"
