# Optional but useful "is it alive" indicator
status_led:
  pin:
    number: GPIO2
    inverted: true

sensor:
  - platform: uptime
    name: "CYD Uptime"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "CYD IP Address"
    ssid:
      name: "CYD Connected SSID"
    mac_address:
      name: "CYD MAC Address"

  - platform: version
    name: "ESPHome Version"
