esphome:
  name: testing-tod
  friendly_name: Testing TOD

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "nJD5lFVrAv0V7PgsBul9UkijTbNcn9zFLFT/aAbw4WQ="

ota:
  - platform: esphome
    password: "9e294791a83c00bc10acc965b90b289d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testing-Tod Fallback Hotspot"
    password: "0cFGuz51WRoy"

captive_portal:
    