#####
# Alert & Notifications Package: Stuff
#####

input_boolean:
  alert_enabled_warn_irregular_off:
    name: "Alert Enabled: Warning - Irregular Off"
    # description: "used to supress warnings during clean event"
    icon: mdi:alert

automation:
  - id: "1736746261434"
    alias: Gill BP New automation
    description: ""
    use_blueprint:
      path: alert_replacement.yaml
      input:
        title: Alert Warn BP New Automation
        label_id: entity_list_aquarium_group_switch
        notification_timer: timer.notification_warn_irregular_off
        controlling_binary_sensor: binary_sensor.alert_state_warn_irregular_off
        alert_type: WARNING
        event_name: ACK_WARN_IRREGULAR_OFF

input_select:
  alert_state_warn_irregular_off:
    name: Alert State
    options:
      - "off"
      - "idle"
      - "active"
      - "acknowledged"
    initial: "off"

template:
  #- use_blueprint:1
  #    path: "label_list_binary_sensor.yaml"
  #   input:
  #    label_id: entity_list_aquarium_group_switch
  #    name: "Test Blueprint Alert"
  # unique_id: "gbt_alert_test_blueprintreal"
  #  state_picker: ["off"]

  - binary_sensor:
      - name: "Alert State: Warning - Irregular Off"
        unique_id: "alert_state_warn_irregular_off"

        state: |
          {%- set my_enabled = bool(is_state( "input_boolean.alert_enabled_warn_irregular_off",'on') ,false) %}
          {%- set my_label = "entity_list_aquarium_group_switch" %}
          {%- set label_list = label_entities(my_label) | select('is_state', 'off') | list  %}    
          {%- set label_count = label_list | count %}
          {{- bool( bool(my_enabled,false) and  bool( label_count | int > 0 ,false) ,false) }}

  #TODO: fix timestamps
