#####
# Alert & Notifications Package: Stuff
#####

input_boolean:
  alert_enabled_warn_irregular_off:
    name: "Alert Enabled: Warning - Irregular Off"
    # description: "used to supress warnings during clean event"
    icon: mdi:alert

automation:
  - id: "1736746261434"
    alias: Gill BP New automation
    description: ""
    use_blueprint:
      path: alert_replacement.yaml
      input:
        title: Alert Warn BP New Automation
        label_id: entity_list_aquarium_group_switch
        notification_timer: timer.notification_warn_irregular_off
        controlling_binary_sensor: binary_sensor.alert_state_warn_irregular_off
        alert_type: WARNING
        event_name: ACK_WARN_IRREGULAR_OFF

template:
  #- use_blueprint:1
  #    path: "label_list_binary_sensor.yaml"
  #   input:
  #    label_id: entity_list_aquarium_group_switch
  #    name: "Test Blueprint Alert"
  # unique_id: "gbt_alert_test_blueprintreal"
  #  state_picker: ["off"]

  - binary_sensor:
      - name: "Alert State: Warning - Irregular Off"
        unique_id: "alert_state_warn_irregular_off"
        state: |
          {%- set my_enabled = bool(is_state( "input_boolean.alert_enabled_warn_irregular_off",'on') ,false) %}
          {%- set my_label = "entity_list_aquarium_group_switch" %}
          {%- set label_list = label_entities(my_label) | select('is_state', 'off') | list  %}    
          {%- set label_count = label_list | count %}
          {{- bool( bool(my_enabled,false) and  bool( label_count | int > 0 ,false) ,false) }}

  #TODO: fix timestamps

alert:
  warn_irregular_off:
    name: "Alert Integration: Warning - Irregular Off" #name of the alert entity
    entity_id: binary_sensor.alert_state_warn_irregular_off
    state: "on"
    repeat: 3
    can_acknowledge: true
    skip_first: true
    #title: "ACK_WARN_IRREGULAR_OFF"
    notifiers:
      - api_dispatch_notification
      - mobile_app_iphone
      #- mobile_app_gillians_ipad
    done_message: "clear_notification"
    data:
      tag: "ACK_WARN_IRREGULAR_OFF" # required for iOS notification replacement
      #target: "iPhone,iPad,alexa,persistant"
      #title: "ACK_WARN_IRREGULAR_OFF"
      actions:
        - action: "ACK_WARN_IRREGULAR_OFF" #to trigger our automation
          title: "Acknowledge Alert (snooze)" #notification but

    message: |
      {%- set my_label = "entity_list_aquarium_group_switch" %}
      {%- set controlling_binary_sensor = 'binary_sensor.alert_state_warn_irregular_off' %}
      {%- set label_list = label_entities(my_label) | select('is_state', 'off') |list %}    
      {%- for entity_id in label_list -%}
        {%- set entity_name = state_attr(entity_id,"friendly_name") %}
        {%- set entity_area_name = area_name(entity_id)  %}
        Entity {{entity_name}} in Area: {{entity_area_name }} \
      {%- endfor %}
